# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: bruno cli CI

on:
  push:
    branches: [ main, 'release*' ]
  pull_request:
    branches: [ main, 'release*', 'dev*' ]

jobs:
  run_bruno_api_test:
    runs-on: ubuntu-latest
    environment: CI
    steps:
    - uses: actions/checkout@v3

    # Install Bruno CLI
    - name: Install Bruno CLI
      run: |
        cd bruno
        npm install -g @usebruno/cli

    # Run Bruno Collection
    - name: Run Bruno Collection
      env:
        DEEPINFRA_API_KEY: ${{ secrets.DEEPINFRA_API_KEY }}
        PROVIDER: ${{ vars.PROVIDER }}
        MODEL_NAME: ${{ vars.MODEL_NAME }}
      run: |
        cd bruno
        bru run --env DeepInfra --env-var PROVIDER=${PROVIDER} --env-var MODEL_NAME=${MODEL_NAME}
